# Generated by Django 3.2 on 2021-08-17 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True)),
                ('branch', models.CharField(choices=[('Select', 'Select'), ('CSE', 'CSE'), ('MECH', 'MECH'), ('CIVEL', 'CIVEL'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('IT', 'IT')], max_length=10, null=True)),
            ],
        ),
    ]
