# Generated by Django 3.2 on 2021-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_alter_students_smobail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='sbranch',
            field=models.CharField(max_length=50),
        ),
    ]
